#	$NetBSD: Makefile,v 1.1 2009/03/26 22:11:44 ad Exp $

.PATH:  ${.CURDIR}/../../dist/lib/libnvpair
.PATH:  ${.CURDIR}/../../dist/common/nvpair

LIB=	nvpair

SRCS=	libnvpair.c nvpair_alloc_system.c nvpair_alloc_fixed.c nvpair.c

.include "../../Makefile.zfs"
.include <bsd.lib.mk>
